### ISSUE TITLE
Prazo de entrega

### ISSUE THREAD

**Issue by AlexandreSA** [Apiki/wordpress-back-end-challenge#3]
Bom dia,

Poderia prorrogar a entrega desse desafio até sexta-feira?
Tive que aprender como criar um plugin e como usar o WP_REST.

Vou aproveitar o feriado para fazer isso, pois a noite está sendo muito curto o meu tempo.

Obrigado

**Comment by elvishp2006** [comment]
Sem problemas @AlexandreSA :)

**Comment by AlexandreSA** [comment]
Obrigado, se eu conseguir terminar antes eu faço um pull request.
